### ISSUE TITLE
Prometheus Image Breaking Changes

### ISSUE THREAD

**Issue by matt328** [robinong79/docker-swarm-monitoring#5]
It looks like a new `prom/prometheus` image was pushed recently that contains many breaking changes with command line args and config file formats.  As a quick fix, the docker-compose file could pull from `:v1.8.2` instead of `:latest`.

As a not so quick fix, a lot of this stack would have to be reconfigured to fix the breaking changes.

**Comment by robinong79** [comment]
Hi Matt,

I will do a change to tag :v1.8.2 as a quick fix.
As my time is limited at the moment I can't provide a solid solution for now, but will look in to it asap.

**Comment by robinong79** [comment]
Sorry for the long wait, but I just updated the repo to Prometheus 2.1.0.
This should fix any future releases for now.
